# Eigenmode simulation of coupled qubits

In [1]:
%load_ext autoreload
%autoreload 2

## Rendering the design

In [2]:
import names as n
import design as d
from qdesignoptimizer.utils.chip_generation import create_chip_base

design, gui = create_chip_base(n.CHIP_NAME, d.chip_type, open_gui=True)
d.render_qiskit_metal_design(design, gui)

## Creating the study and optimization targets

In [3]:
import mini_studies as ms
import optimization_targets as ot

In [4]:
MINI_STUDY_GROUP = [n.NBR_1, n.NBR_2]
MINI_STUDY = ms.get_mini_study_2qb_resonator_coupler()
RENDER_QISKIT_METAL = lambda design: d.render_qiskit_metal_design(design, gui)

opt_targets = ot.get_opt_targets_2qubits_resonator_coupler(
    groups=MINI_STUDY_GROUP,
    opt_target_qubit_freq=True,
    opt_target_qubit_anharm=True,
    opt_target_resonator_freq=True,
    opt_target_resonator_kappa=False,
    opt_target_resonator_qubit_chi=True,
    opt_target_coupler_freq=True,
    opt_target_coupler_anharm=True,
    opt_target_coupler_qubit_chi=True,
    use_simple_resonator_qubit_chi_relation=False,
)
# attributes = [
#     "qiskit_component_names",
#     "port_list",
#     "open_pins",
#     "modes",
#     "jj_setup",
#     "design_name",
#     "adjustment_rate",
#     "cos_trunc",
#     "fock_trunc",
#     "build_fine_mesh",
#     "nbr_passes",
#     "delta_f"
# ]

# for attr in attributes:
#     print(f"{attr}: {getattr(MINI_STUDY, attr)}")

## Creating design analysis objects

In [5]:
import time
import numpy as np
import parameter_targets as pt
import plot_settings as ps

from qdesignoptimizer.design_analysis import DesignAnalysis, DesignAnalysisState
from qdesignoptimizer.utils.utils import get_save_path

# Closing Ansys hfss
from qdesignoptimizer.utils.utils import close_ansys

close_ansys()

In [6]:
design_analysis_state = DesignAnalysisState(
    design, RENDER_QISKIT_METAL, pt.PARAM_TARGETS
)

design_analysis = DesignAnalysis(
    design_analysis_state,
    mini_study=MINI_STUDY,
    opt_targets=opt_targets,
    save_path=get_save_path("out/", n.CHIP_NAME),
    update_design_variables=False,
    plot_settings=ps.PLOT_SETTINGS_TWO_QB,
)

[INFO|2025-08-23 15:39:05]: self.eig_solver.sim.setup 
{
    "name": "Resonator_setup",
    "reuse_selected_design": true,
    "reuse_setup": true,
    "min_freq_ghz": 1,
    "n_modes": 1,
    "max_delta_f": 0.5,
    "max_passes": 10,
    "min_passes": 1,
    "min_converged": 1,
    "pct_refinement": 30,
    "basis_order": 1,
    "vars": {
        "Lj": "10 nH",
        "Cj": "0 fF"
    }
}
INFO 03:39PM [connect_project]: Connecting to Ansys Desktop API...
INFO 03:39PM [load_ansys_project]: 	Opened Ansys App
INFO 03:39PM [load_ansys_project]: 	Opened Ansys Desktop v2021.1.0
INFO 03:39PM [load_ansys_project]: 	Opened Ansys Project
	Folder:    D:/Ansys/Ansoft/
	Project:   Project466
INFO 03:39PM [connect_design]: No active design found (or error getting active design).
INFO 03:39PM [connect]: 	 Connected to project "Project466". No design detected
03:39PM 15s WARNING [activate_ansys_design]: The design_name=get_mini_study_2qb_resonator_coupler was not in active project.  Designs in activ

## Optimization step

In [7]:
# number of runs of optimization and number of passes for simulation at each run
nbr_iterations = 10
group_passes_start = 17
group_passes_stop = 15
delta_f = 0.001
for i in range(nbr_iterations):
    design_analysis.update_nbr_passes(
        group_passes_start  # min(group_passes_start + i, group_passes_stop)
    )  # successive increase of number of passes for faster convergence [8, 9, 10, 11, 12, 13, 14, 15, 15, 15]
    design_analysis.update_delta_f(delta_f)
    design_analysis.optimize_target({}, {})
    design_analysis.screenshot(gui=gui, run=i)

[INFO|2025-08-23 15:39:18]: Updated_design_vars
{
    "cpw_width": "10 um",
    "cpw_gap": "6 um",
    "design_var_width_qubit_1": "180um",
    "design_var_width_qubit_2": "180um",
    "design_var_length_coupler_1to2": "250um",
    "design_var_length_resonator_1_capacitance": "15um",
    "design_var_length_resonator_2_capacitance": "15um",
    "design_var_lj_qubit_1": "10nH",
    "design_var_lj_qubit_2": "12nH",
    "design_var_lj_coupler_1to2": "2.0nH",
    "design_var_cj_qubit_1": "0fF",
    "design_var_cj_qubit_2": "0fF",
    "design_var_cj_coupler_1to2": "0fF",
    "design_var_length_resonator_1": "4200um",
    "design_var_length_resonator_2": "4200um",
    "design_var_coupl_length_qubit_1_resonator_1": "50um",
    "design_var_coupl_length_qubit_2_resonator_2": "50um",
    "design_var_coupl_length_coupler_1to2_qubit_1": "13um",
    "design_var_coupl_length_coupler_1to2_qubit_2": "15um",
    "design_var_coupl_length_resonator_1_tee": "400um",
    "design_var_coupl_length_resonator_2

Initializing new desktop!
PyAEDT INFO: StdOut is enabled
PyAEDT INFO: Log on file is enabled
PyAEDT INFO: Log on Desktop Message Manager is enabled
PyAEDT INFO: Debug logger is disabled. PyAEDT methods will not be logged.
PyAEDT INFO: Launching PyAEDT outside AEDT with CPython and PythonNET.
PyAEDT INFO: AEDT installation Path C:\Program Files\AnsysEM\AnsysEM21.1\Win64.
PyAEDT INFO: Launching AEDT with COM plugin using PythonNET.
PyAEDT WARNING: PyAEDT is not supported in AEDT versions earlier than 2021 R2. Trying to launch PyAEDT with PyWin32.
PyAEDT INFO: pyaedt v0.6.94
PyAEDT INFO: Python version 3.10.16 | packaged by conda-forge | (main, Dec  5 2024, 14:07:43) [MSC v.1942 64 bit (AMD64)]
PyAEDT INFO: AEDT 2021.1.0 Build Date 2020-11-16 21:49:12
PyAEDT INFO: No project is defined. Project Project466 exists and has been read.
PyAEDT INFO: Active Design set to get_mini_study_2qb_resonator_coupler
PyAEDT INFO: Aedt Objects correctly read


INFO 03:39PM [analyze]: Analyzing setup Setup


Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1

        energy_elec_all       = 3.1989909779825e-25
        energy_elec_substrate = 2.94088118456034e-25
        EPR of substrate = 91.9%

        energy_mag    = 2.8229525690229e-27
        energy_mag % of energy_elec_all  = 0.9%
        

Variation 0  [1/1]

  Mode 0 at 4.57 GHz   [1/5]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               99.1%  1.599e-25 1.411e-27

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_0j   sign s_0j

WARNING 04:06PM [__init__]: <p>Error: <class 'IndexError'></p>



ANALYSIS DONE. Data saved to:

C:\data-pyEPR\Project466\get_mini_study_2qb_resonator_coupler\2025-08-23 16-04-54.npz


	 Differences in variations:



 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Variation 0

C:\Users\marer\Anaconda3\envs\qdesignenv\Lib\site-packages\pyEPR\core_quantum_analysis.py
PJ (5, 3) SJ (5, 3) EJ (3, 3) PHI_zpf (5, 3) PJ_cap (5, 3)
PJ [[2.40726093e-07 9.89340885e-01 1.87453520e-03]
 [9.85232047e-01 7.76474078e-06 4.00032807e-03]
 [4.47937367e-03 2.08345510e-03 9.08557757e-01]
 [1.57278622e-04 1.20199852e-04 1.19243401e-06]
 [2.83096733e-04 1.25030153e-04 1.01499780e-03]]
SJ [[ 1 -1 -1]
 [-1  1 -1]
 [ 1  1 -1]
 [-1  1 -1]
 [ 1  1 -1]]
Om [[4.57027088 0.         0.         0.         0.        ]
 [0.         5.00037431 0.         0.         0.        ]
 [0.         0.         6.44247951 0.         0.        ]
 [0.         0.         0.         6.65451362 0.        ]
 [0.         0.         0.         0.         6.65476227]]
EJ

[INFO|2025-08-23 16:07:36]: freq_ND_results
{
    "0": {
        "0": 4376.066337291257,
        "1": 4807.989709674118,
        "2": 6387.844261814678,
        "3": 6654.443619917438,
        "4": 6654.620422234528
    }
}
04:07PM 36s CRITICAL [_qt_message_handler]: line: 0, func: None(), file: None  CRITICAL: QEventDispatcherWin32::wakeUp: Failed to post a message (Not enough quota is available to process this command.)

[WARNING|2025-08-23 16:07:39]: The optimized value for the design variable design_var_coupl_length_qubit_1_resonator_1: 80.0 is at the bounds. Consider changing the bounds or making the initial design closer to the optimal one.
[INFO|2025-08-23 16:07:39]: Updated_design_vars
{
    "design_var_lj_coupler_1to2": "4.7934619260629265 nH",
    "design_var_length_coupler_1to2": "143.29675429223053 um",
    "design_var_lj_qubit_1": "17.24653724367522 nH",
    "design_var_width_qubit_1": "139.4154792983929 um",
    "design_var_length_resonator_1": "3925.478340308799 um",
   

Returning found desktop with PID 31628!
PyAEDT INFO: No project is defined. Project Project466 exists and has been read.
PyAEDT INFO: Active Design set to get_mini_study_2qb_resonator_coupler
PyAEDT INFO: Aedt Objects correctly read


INFO 04:07PM [analyze]: Analyzing setup Setup


Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1

        energy_elec_all       = 2.39345767569371e-25
        energy_elec_substrate = 2.20408280788606e-25
        EPR of substrate = 92.1%

        energy_mag    = 2.39251953274313e-25
        energy_mag % of energy_elec_all  = 100.0%
        

Variation 0  [1/1]

  Mode 0 at 4.20 GHz   [1/5]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               99.5%  1.178e-25 6.182e-28

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_0j   sign 

WARNING 04:33PM [__init__]: <p>Error: <class 'IndexError'></p>



ANALYSIS DONE. Data saved to:

C:\data-pyEPR\Project466\get_mini_study_2qb_resonator_coupler\2025-08-23 16-31-09.npz


	 Differences in variations:



 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Variation 0

C:\Users\marer\Anaconda3\envs\qdesignenv\Lib\site-packages\pyEPR\core_quantum_analysis.py
PJ (5, 3) SJ (5, 3) EJ (3, 3) PHI_zpf (5, 3) PJ_cap (5, 3)
PJ [[2.61308736e-04 9.87681799e-01 6.69614958e-03]
 [9.85387337e-01 5.80290684e-04 8.30557658e-03]
 [9.02506561e-03 6.68887781e-03 9.58566873e-01]
 [5.59754918e-08 2.61159224e-04 1.06060330e-05]
 [3.83341722e-04 1.00920226e-07 1.17528634e-05]]
SJ [[-1 -1 -1]
 [ 1 -1  1]
 [-1 -1  1]
 [-1 -1  1]
 [-1 -1  1]]
Om [[4.19980454 0.         0.         0.         0.        ]
 [0.         4.36654813 0.         0.         0.        ]
 [0.         0.         5.21633557 0.         0.        ]
 [0.         0.         0.         6.9796688  0.        ]
 [0.         0.         0.         0.         7.00291884]]
EJ

[INFO|2025-08-23 16:34:01]: freq_ND_results
{
    "0": {
        "0": 3953.417004328567,
        "1": 4107.730589566549,
        "2": 5117.82864315638,
        "3": 6979.566539021756,
        "4": 7002.768438203897
    }
}
04:34PM 02s CRITICAL [_qt_message_handler]: line: 0, func: None(), file: None  CRITICAL: QEventDispatcherWin32::wakeUp: Failed to post a message (Not enough quota is available to process this command.)

[INFO|2025-08-23 16:34:04]: Updated_design_vars
{
    "design_var_lj_coupler_1to2": "4.291773760474574 nH",
    "design_var_length_coupler_1to2": "141.13258215454542 um",
    "design_var_lj_qubit_1": "17.248863010459637 nH",
    "design_var_width_qubit_1": "135.91571698647144 um",
    "design_var_length_resonator_1": "3860.8449193852452 um",
    "design_var_coupl_length_qubit_1_resonator_1": "63.65823036842411 um",
    "design_var_coupl_length_coupler_1to2_qubit_1": "6.087035943602029 um",
    "design_var_lj_qubit_2": "17.80871103683254 nH",
    "design_var_width_qubi

Returning found desktop with PID 31628!
PyAEDT INFO: No project is defined. Project Project466 exists and has been read.
PyAEDT INFO: Active Design set to get_mini_study_2qb_resonator_coupler
PyAEDT INFO: Aedt Objects correctly read


INFO 04:34PM [analyze]: Analyzing setup Setup


Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1

        energy_elec_all       = 1.79823823292509e-25
        energy_elec_substrate = 1.65618285275389e-25
        EPR of substrate = 92.1%

        energy_mag    = 1.7977296186115e-25
        energy_mag % of energy_elec_all  = 100.0%
        

Variation 0  [1/1]

  Mode 0 at 4.26 GHz   [1/5]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               99.5%  1.447e-25 7.419e-28

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_0j   sign s

WARNING 05:02PM [__init__]: <p>Error: <class 'IndexError'></p>



ANALYSIS DONE. Data saved to:

C:\data-pyEPR\Project466\get_mini_study_2qb_resonator_coupler\2025-08-23 16-59-47.npz


	 Differences in variations:



 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Variation 0

C:\Users\marer\Anaconda3\envs\qdesignenv\Lib\site-packages\pyEPR\core_quantum_analysis.py
PJ (5, 3) SJ (5, 3) EJ (3, 3) PHI_zpf (5, 3) PJ_cap (5, 3)
PJ [[2.39626881e-04 9.89075596e-01 5.46640230e-03]
 [9.87798455e-01 4.74528159e-04 6.33242886e-03]
 [6.92293861e-03 5.52075785e-03 9.58687572e-01]
 [9.66782107e-08 2.19830771e-04 1.54637985e-05]
 [2.68589597e-04 9.62449656e-08 1.41358863e-05]]
SJ [[-1 -1 -1]
 [ 1 -1  1]
 [-1 -1  1]
 [-1 -1  1]
 [-1 -1  1]]
Om [[4.25607966 0.         0.         0.         0.        ]
 [0.         4.42161706 0.         0.         0.        ]
 [0.         0.         5.54657972 0.         0.        ]
 [0.         0.         0.         7.09630185 0.        ]
 [0.         0.         0.         0.         7.16477458]]
EJ

[INFO|2025-08-23 17:02:48]: freq_ND_results
{
    "0": {
        "0": 4001.683240927202,
        "1": 4155.7582688541015,
        "2": 5447.841232639277,
        "3": 7096.21210108272,
        "4": 7164.664537535423
    }
}
05:02PM 48s CRITICAL [_qt_message_handler]: line: 0, func: None(), file: None  CRITICAL: QEventDispatcherWin32::wakeUp: Failed to post a message (Not enough quota is available to process this command.)

[INFO|2025-08-23 17:02:51]: Updated_design_vars
{
    "design_var_lj_coupler_1to2": "4.301602913321889 nH",
    "design_var_length_coupler_1to2": "140.69856594994295 um",
    "design_var_lj_qubit_1": "17.25218251448815 nH",
    "design_var_width_qubit_1": "135.61258835783227 um",
    "design_var_length_resonator_1": "3885.0644189034347 um",
    "design_var_coupl_length_qubit_1_resonator_1": "59.10858753730678 um",
    "design_var_coupl_length_coupler_1to2_qubit_1": "5.622295579928196 um",
    "design_var_lj_qubit_2": "17.815040487594835 nH",
    "design_var_width_qub

Returning found desktop with PID 31628!
PyAEDT INFO: No project is defined. Project Project466 exists and has been read.
PyAEDT INFO: Active Design set to get_mini_study_2qb_resonator_coupler
PyAEDT INFO: Aedt Objects correctly read


INFO 05:03PM [analyze]: Analyzing setup Setup


Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1

        energy_elec_all       = 1.65397089249087e-25
        energy_elec_substrate = 1.52340158870422e-25
        EPR of substrate = 92.1%

        energy_mag    = 1.6535455342265e-25
        energy_mag % of energy_elec_all  = 100.0%
        

Variation 0  [1/1]

  Mode 0 at 4.26 GHz   [1/5]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               99.5%  1.274e-25 6.531e-28

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_0j   sign s

WARNING 05:32PM [__init__]: <p>Error: <class 'IndexError'></p>



ANALYSIS DONE. Data saved to:

C:\data-pyEPR\Project466\get_mini_study_2qb_resonator_coupler\2025-08-23 17-30-37.npz


	 Differences in variations:



 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Variation 0

C:\Users\marer\Anaconda3\envs\qdesignenv\Lib\site-packages\pyEPR\core_quantum_analysis.py
PJ (5, 3) SJ (5, 3) EJ (3, 3) PHI_zpf (5, 3) PJ_cap (5, 3)
PJ [[3.06039685e-04 9.88616736e-01 5.85403281e-03]
 [9.87563875e-01 5.82967791e-04 6.58258118e-03]
 [7.21811796e-03 5.88480736e-03 9.58699838e-01]
 [9.15056095e-08 2.02382826e-04 1.42017447e-05]
 [2.44299607e-04 9.64197134e-08 1.30601990e-05]]
SJ [[-1 -1 -1]
 [-1  1 -1]
 [ 1  1 -1]
 [-1 -1  1]
 [-1 -1  1]]
Om [[4.2554152  0.         0.         0.         0.        ]
 [0.         4.4122254  0.         0.         0.        ]
 [0.         0.         5.51948592 0.         0.        ]
 [0.         0.         0.         7.08269712 0.        ]
 [0.         0.         0.         0.         7.13620237]]
EJ

[INFO|2025-08-23 17:33:34]: freq_ND_results
{
    "0": {
        "0": 4001.039455987764,
        "1": 4147.423177614547,
        "2": 5421.229151557948,
        "3": 7082.614671166352,
        "4": 7136.102872000065
    }
}
05:33PM 34s CRITICAL [_qt_message_handler]: line: 0, func: None(), file: None  CRITICAL: QEventDispatcherWin32::wakeUp: Failed to post a message (Not enough quota is available to process this command.)

[INFO|2025-08-23 17:33:38]: Updated_design_vars
{
    "design_var_lj_coupler_1to2": "4.299692251163778 nH",
    "design_var_length_coupler_1to2": "139.2787943607556 um",
    "design_var_lj_qubit_1": "17.246779510191658 nH",
    "design_var_width_qubit_1": "134.83614391520845 um",
    "design_var_length_resonator_1": "3893.851030204758 um",
    "design_var_coupl_length_qubit_1_resonator_1": "57.828737504637665 um",
    "design_var_coupl_length_coupler_1to2_qubit_1": "5.203093814402229 um",
    "design_var_lj_qubit_2": "17.81756363063134 nH",
    "design_var_width_qubi

Returning found desktop with PID 31628!
PyAEDT INFO: No project is defined. Project Project466 exists and has been read.
PyAEDT INFO: Active Design set to get_mini_study_2qb_resonator_coupler
PyAEDT INFO: Aedt Objects correctly read


INFO 05:33PM [analyze]: Analyzing setup Setup


Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1

        energy_elec_all       = 1.92716882117556e-25
        energy_elec_substrate = 1.77501178547908e-25
        EPR of substrate = 92.1%

        energy_mag    = 1.92670073376875e-25
        energy_mag % of energy_elec_all  = 100.0%
        

Variation 0  [1/1]

  Mode 0 at 4.26 GHz   [1/5]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               99.5%  6.294e-26 3.203e-28

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_0j   sign 

WARNING 06:02PM [__init__]: <p>Error: <class 'IndexError'></p>



ANALYSIS DONE. Data saved to:

C:\data-pyEPR\Project466\get_mini_study_2qb_resonator_coupler\2025-08-23 18-00-06.npz


	 Differences in variations:



 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Variation 0

C:\Users\marer\Anaconda3\envs\qdesignenv\Lib\site-packages\pyEPR\core_quantum_analysis.py
PJ (5, 3) SJ (5, 3) EJ (3, 3) PHI_zpf (5, 3) PJ_cap (5, 3)
PJ [[2.43975587e-04 9.88866661e-01 5.70173738e-03]
 [9.87487536e-01 4.95353833e-04 6.73334482e-03]
 [7.36321585e-03 5.75345483e-03 9.58370360e-01]
 [1.06674807e-07 1.98372445e-04 1.53402426e-05]
 [2.46342182e-04 1.19484100e-07 1.55025984e-05]]
SJ [[-1 -1 -1]
 [ 1 -1  1]
 [-1 -1  1]
 [-1 -1  1]
 [-1 -1  1]]
Om [[4.25666271 0.         0.         0.         0.        ]
 [0.         4.43526915 0.         0.         0.        ]
 [0.         0.         5.57301391 0.         0.        ]
 [0.         0.         0.         7.08455112 0.        ]
 [0.         0.         0.         0.         7.12727636]]
EJ

[INFO|2025-08-23 18:03:02]: freq_ND_results
{
    "0": {
        "0": 4002.056971826659,
        "1": 4167.727999191657,
        "2": 5472.957083931523,
        "3": 7084.470075077948,
        "4": 7127.175576394418
    }
}
06:03PM 02s CRITICAL [_qt_message_handler]: line: 0, func: None(), file: None  CRITICAL: QEventDispatcherWin32::wakeUp: Failed to post a message (Not enough quota is available to process this command.)

[INFO|2025-08-23 18:03:05]: Updated_design_vars
{
    "design_var_lj_coupler_1to2": "4.303369535021262 nH",
    "design_var_length_coupler_1to2": "140.33461601559955 um",
    "design_var_lj_qubit_1": "17.250118494018707 nH",
    "design_var_width_qubit_1": "135.31138200894992 um",
    "design_var_length_resonator_1": "3893.8510307328984 um",
    "design_var_coupl_length_qubit_1_resonator_1": "57.70684577362798 um",
    "design_var_coupl_length_coupler_1to2_qubit_1": "5.271258061396997 um",
    "design_var_lj_qubit_2": "17.818894258659597 nH",
    "design_var_width_qu

Returning found desktop with PID 31628!
PyAEDT INFO: No project is defined. Project Project466 exists and has been read.
PyAEDT INFO: Active Design set to get_mini_study_2qb_resonator_coupler
PyAEDT INFO: Aedt Objects correctly read


INFO 06:03PM [analyze]: Analyzing setup Setup


Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1

        energy_elec_all       = 2.19791137483417e-25
        energy_elec_substrate = 2.02394923821716e-25
        EPR of substrate = 92.1%

        energy_mag    = 2.19735677983521e-25
        energy_mag % of energy_elec_all  = 100.0%
        

Variation 0  [1/1]

  Mode 0 at 4.25 GHz   [1/5]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               99.5%  1.126e-25 5.712e-28

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_0j   sign 

WARNING 06:29PM [__init__]: <p>Error: <class 'IndexError'></p>



ANALYSIS DONE. Data saved to:

C:\data-pyEPR\Project466\get_mini_study_2qb_resonator_coupler\2025-08-23 18-27-25.npz


	 Differences in variations:



 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Variation 0

C:\Users\marer\Anaconda3\envs\qdesignenv\Lib\site-packages\pyEPR\core_quantum_analysis.py
PJ (5, 3) SJ (5, 3) EJ (3, 3) PHI_zpf (5, 3) PJ_cap (5, 3)
PJ [[2.49338949e-04 9.88815685e-01 5.77234368e-03]
 [9.87528667e-01 5.04023514e-04 6.69788429e-03]
 [7.32390554e-03 5.82493298e-03 9.58360831e-01]
 [1.00253213e-07 1.97526732e-04 1.52954043e-05]
 [2.39616411e-04 9.96002000e-08 1.37643506e-05]]
SJ [[-1 -1 -1]
 [ 1 -1  1]
 [ 1  1 -1]
 [-1 -1  1]
 [ 1  1 -1]]
Om [[4.25107329 0.         0.         0.         0.        ]
 [0.         4.42783076 0.         0.         0.        ]
 [0.         0.         5.55391951 0.         0.        ]
 [0.         0.         0.         7.07185807 0.        ]
 [0.         0.         0.         0.         7.12829081]]
EJ

[INFO|2025-08-23 18:30:21]: freq_ND_results
{
    "0": {
        "0": 3997.1214678636297,
        "1": 4161.1493005286975,
        "2": 5454.451415378001,
        "3": 7071.777624174873,
        "4": 7128.193016171803
    }
}
06:30PM 21s CRITICAL [_qt_message_handler]: line: 0, func: None(), file: None  CRITICAL: QEventDispatcherWin32::wakeUp: Failed to post a message (Not enough quota is available to process this command.)

[INFO|2025-08-23 18:30:24]: Updated_design_vars
{
    "design_var_lj_coupler_1to2": "4.303196167010912 nH",
    "design_var_length_coupler_1to2": "140.56961605420017 um",
    "design_var_lj_qubit_1": "17.2480822145958 nH",
    "design_var_width_qubit_1": "135.40213699087047 um",
    "design_var_length_resonator_1": "3893.8510313346605 um",
    "design_var_coupl_length_qubit_1_resonator_1": "57.99287675315918 um",
    "design_var_coupl_length_coupler_1to2_qubit_1": "5.17554065135772 um",
    "design_var_lj_qubit_2": "17.817388272626243 nH",
    "design_var_width_qub

Returning found desktop with PID 31628!
PyAEDT INFO: No project is defined. Project Project466 exists and has been read.
PyAEDT INFO: Active Design set to get_mini_study_2qb_resonator_coupler
PyAEDT INFO: Aedt Objects correctly read


INFO 06:30PM [analyze]: Analyzing setup Setup


Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1

        energy_elec_all       = 1.99400747547473e-25
        energy_elec_substrate = 1.83628593569372e-25
        EPR of substrate = 92.1%

        energy_mag    = 1.99350848176417e-25
        energy_mag % of energy_elec_all  = 100.0%
        

Variation 0  [1/1]

  Mode 0 at 4.25 GHz   [1/5]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               99.5%  1.423e-25 7.181e-28

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_0j   sign 

WARNING 06:59PM [__init__]: <p>Error: <class 'IndexError'></p>



ANALYSIS DONE. Data saved to:

C:\data-pyEPR\Project466\get_mini_study_2qb_resonator_coupler\2025-08-23 18-57-05.npz


	 Differences in variations:



 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Variation 0

C:\Users\marer\Anaconda3\envs\qdesignenv\Lib\site-packages\pyEPR\core_quantum_analysis.py
PJ (5, 3) SJ (5, 3) EJ (3, 3) PHI_zpf (5, 3) PJ_cap (5, 3)
PJ [[3.23037761e-04 9.88572388e-01 5.95502116e-03]
 [9.87462383e-01 6.12291948e-04 6.70594805e-03]
 [7.36261499e-03 5.98068524e-03 9.58661969e-01]
 [9.39407072e-08 1.98415782e-04 1.44583088e-05]
 [2.36442767e-04 9.85174447e-08 1.33902738e-05]]
SJ [[-1 -1 -1]
 [ 1 -1  1]
 [ 1  1 -1]
 [ 1  1 -1]
 [ 1  1 -1]]
Om [[4.24914092 0.         0.         0.         0.        ]
 [0.         4.40858354 0.         0.         0.        ]
 [0.         0.         5.52043948 0.         0.        ]
 [0.         0.         0.         7.07171737 0.        ]
 [0.         0.         0.         0.         7.12723668]]
EJ

[INFO|2025-08-23 19:00:12]: freq_ND_results
{
    "0": {
        "0": 3995.456054977734,
        "1": 4144.268442298513,
        "2": 5422.032079496912,
        "3": 7071.636698626394,
        "4": 7127.1405199696255
    }
}
07:00PM 12s CRITICAL [_qt_message_handler]: line: 0, func: None(), file: None  CRITICAL: QEventDispatcherWin32::wakeUp: Failed to post a message (Not enough quota is available to process this command.)

[INFO|2025-08-23 19:00:15]: Updated_design_vars
{
    "design_var_lj_coupler_1to2": "4.299680150589685 nH",
    "design_var_length_coupler_1to2": "139.24450403964912 um",
    "design_var_lj_qubit_1": "17.243768586382977 nH",
    "design_var_width_qubit_1": "134.413704171554 um",
    "design_var_length_resonator_1": "3893.85103186027 um",
    "design_var_coupl_length_qubit_1_resonator_1": "57.722555988722995 um",
    "design_var_coupl_length_coupler_1to2_qubit_1": "4.923259217611342 um",
    "design_var_lj_qubit_2": "17.815645539741315 nH",
    "design_var_width_qubi

Returning found desktop with PID 31628!
PyAEDT INFO: No project is defined. Project Project466 exists and has been read.
PyAEDT INFO: Active Design set to get_mini_study_2qb_resonator_coupler
PyAEDT INFO: Aedt Objects correctly read


INFO 07:00PM [analyze]: Analyzing setup Setup


Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1

        energy_elec_all       = 2.15352673375183e-25
        energy_elec_substrate = 1.98296797884294e-25
        EPR of substrate = 92.1%

        energy_mag    = 2.15295843472131e-25
        energy_mag % of energy_elec_all  = 100.0%
        

Variation 0  [1/1]

  Mode 0 at 4.26 GHz   [1/5]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               99.5%  9.147e-26 4.633e-28

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_0j   sign 

WARNING 07:26PM [__init__]: <p>Error: <class 'IndexError'></p>



ANALYSIS DONE. Data saved to:

C:\data-pyEPR\Project466\get_mini_study_2qb_resonator_coupler\2025-08-23 19-24-13.npz


	 Differences in variations:



 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Variation 0

C:\Users\marer\Anaconda3\envs\qdesignenv\Lib\site-packages\pyEPR\core_quantum_analysis.py
PJ (5, 3) SJ (5, 3) EJ (3, 3) PHI_zpf (5, 3) PJ_cap (5, 3)
PJ [[2.15343134e-04 9.88824294e-01 5.79466604e-03]
 [9.87084490e-01 4.63782410e-04 7.08502914e-03]
 [7.72447165e-03 5.85390642e-03 9.57946075e-01]
 [1.05391410e-07 1.98022272e-04 1.58137315e-05]
 [2.48879991e-04 1.06337200e-07 1.46453203e-05]]
SJ [[-1 -1 -1]
 [ 1 -1  1]
 [-1 -1  1]
 [-1 -1  1]
 [-1 -1  1]]
Om [[4.25536391 0.         0.         0.         0.        ]
 [0.         4.45253867 0.         0.         0.        ]
 [0.         0.         5.56785571 0.         0.        ]
 [0.         0.         0.         7.07279468 0.        ]
 [0.         0.         0.         0.         7.12977208]]
EJ

[INFO|2025-08-23 19:27:46]: freq_ND_results
{
    "0": {
        "0": 4000.9376245766102,
        "1": 4182.994245012571,
        "2": 5467.884378645874,
        "3": 7072.7139094882905,
        "4": 7129.670090526287
    }
}
07:27PM 47s CRITICAL [_qt_message_handler]: line: 0, func: None(), file: None  CRITICAL: QEventDispatcherWin32::wakeUp: Failed to post a message (Not enough quota is available to process this command.)

[INFO|2025-08-23 19:27:51]: Updated_design_vars
{
    "design_var_lj_coupler_1to2": "4.305734898475523 nH",
    "design_var_length_coupler_1to2": "139.9627223279253 um",
    "design_var_lj_qubit_1": "17.250013985804806 nH",
    "design_var_width_qubit_1": "135.85456717968577 um",
    "design_var_length_resonator_1": "3893.851032568838 um",
    "design_var_coupl_length_qubit_1_resonator_1": "58.125101216464714 um",
    "design_var_coupl_length_coupler_1to2_qubit_1": "5.029844365608756 um",
    "design_var_lj_qubit_2": "17.819465322855176 nH",
    "design_var_width_q

Returning found desktop with PID 31628!
PyAEDT INFO: No project is defined. Project Project466 exists and has been read.
PyAEDT INFO: Active Design set to get_mini_study_2qb_resonator_coupler
PyAEDT INFO: Aedt Objects correctly read


INFO 07:28PM [analyze]: Analyzing setup Setup


Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1

        energy_elec_all       = 1.83116628029563e-25
        energy_elec_substrate = 1.68635655728659e-25
        EPR of substrate = 92.1%

        energy_mag    = 1.83074597245578e-25
        energy_mag % of energy_elec_all  = 100.0%
        

Variation 0  [1/1]

  Mode 0 at 4.26 GHz   [1/5]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               99.5%  1.158e-25 5.918e-28

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_0j   sign 

WARNING 07:58PM [__init__]: <p>Error: <class 'IndexError'></p>



ANALYSIS DONE. Data saved to:

C:\data-pyEPR\Project466\get_mini_study_2qb_resonator_coupler\2025-08-23 19-56-05.npz


	 Differences in variations:



 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Variation 0

C:\Users\marer\Anaconda3\envs\qdesignenv\Lib\site-packages\pyEPR\core_quantum_analysis.py
PJ (5, 3) SJ (5, 3) EJ (3, 3) PHI_zpf (5, 3) PJ_cap (5, 3)
PJ [[3.98843210e-04 9.88415174e-01 5.96820200e-03]
 [9.87530970e-01 7.11283205e-04 6.53280122e-03]
 [7.21018677e-03 5.97443342e-03 9.58042504e-01]
 [1.03769975e-07 2.01280769e-04 1.55233823e-05]
 [2.37800421e-04 1.09440654e-07 1.49935066e-05]]
SJ [[-1 -1 -1]
 [-1  1 -1]
 [ 1  1 -1]
 [-1 -1  1]
 [ 1  1 -1]]
Om [[4.26133472 0.         0.         0.         0.        ]
 [0.         4.40956547 0.         0.         0.        ]
 [0.         0.         5.56370511 0.         0.        ]
 [0.         0.         0.         7.07013771 0.        ]
 [0.         0.         0.         0.         7.1280153 ]]
EJ

[INFO|2025-08-23 19:59:17]: freq_ND_results
{
    "0": {
        "0": 4006.158453832982,
        "1": 4145.073217665554,
        "2": 5463.888797261481,
        "3": 7070.0556146522185,
        "4": 7127.918364331706
    }
}
07:59PM 18s CRITICAL [_qt_message_handler]: line: 0, func: None(), file: None  CRITICAL: QEventDispatcherWin32::wakeUp: Failed to post a message (Not enough quota is available to process this command.)

[INFO|2025-08-23 19:59:21]: Updated_design_vars
{
    "design_var_lj_coupler_1to2": "4.306452719169251 nH",
    "design_var_length_coupler_1to2": "140.6535474237085 um",
    "design_var_lj_qubit_1": "17.244084870795604 nH",
    "design_var_width_qubit_1": "134.92774798925703 um",
    "design_var_length_resonator_1": "3893.851033150664 um",
    "design_var_coupl_length_qubit_1_resonator_1": "57.72836578382665 um",
    "design_var_coupl_length_coupler_1to2_qubit_1": "5.1045783667666695 um",
    "design_var_lj_qubit_2": "17.820085772161928 nH",
    "design_var_width_qu

Returning found desktop with PID 31628!
PyAEDT INFO: No project is defined. Project Project466 exists and has been read.
PyAEDT INFO: Active Design set to get_mini_study_2qb_resonator_coupler
PyAEDT INFO: Aedt Objects correctly read


INFO 07:59PM [analyze]: Analyzing setup Setup


Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1
Design "get_mini_study_2qb_resonator_coupler" info:
	# eigenmodes    5
	# variations    1

        energy_elec_all       = 2.20631285479638e-25
        energy_elec_substrate = 2.03180264713447e-25
        EPR of substrate = 92.1%

        energy_mag    = 2.20574273773867e-25
        energy_mag % of energy_elec_all  = 100.0%
        

Variation 0  [1/1]

  Mode 0 at 4.25 GHz   [1/5]
    Calculating ℰ_magnetic,ℰ_electric
       (ℰ_E-ℰ_H)/ℰ_E       ℰ_E       ℰ_H
               99.5%  7.996e-26 4.057e-28

    Calculating junction energy participation ration (EPR)
	method=`line_voltage`. First estimates:
	junction        EPR p_0j   sign 

WARNING 08:29PM [__init__]: <p>Error: <class 'IndexError'></p>



ANALYSIS DONE. Data saved to:

C:\data-pyEPR\Project466\get_mini_study_2qb_resonator_coupler\2025-08-23 20-27-28.npz


	 Differences in variations:



 . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . . 
Variation 0

C:\Users\marer\Anaconda3\envs\qdesignenv\Lib\site-packages\pyEPR\core_quantum_analysis.py
PJ (5, 3) SJ (5, 3) EJ (3, 3) PHI_zpf (5, 3) PJ_cap (5, 3)
PJ [[2.29593739e-04 9.88788810e-01 5.80782318e-03]
 [9.87206060e-01 4.83063078e-04 6.99842254e-03]
 [7.64475274e-03 5.86400951e-03 9.57708526e-01]
 [1.02677131e-07 1.96523640e-04 1.54804735e-05]
 [2.46019407e-04 1.03796137e-07 1.43887724e-05]]
SJ [[ 1  1  1]
 [-1  1 -1]
 [ 1  1 -1]
 [-1 -1  1]
 [-1 -1  1]]
Om [[4.2485009  0.         0.         0.         0.        ]
 [0.         4.43945639 0.         0.         0.        ]
 [0.         0.         5.55568028 0.         0.        ]
 [0.         0.         0.         7.07193548 0.        ]
 [0.         0.         0.         0.         7.12707205]]
EJ

[INFO|2025-08-23 20:30:40]: freq_ND_results
{
    "0": {
        "0": 3994.850515038946,
        "1": 4171.480159866422,
        "2": 5456.071159634316,
        "3": 7071.8554380076675,
        "4": 7126.971483607424
    }
}
08:30PM 41s CRITICAL [_qt_message_handler]: line: 0, func: None(), file: None  CRITICAL: QEventDispatcherWin32::wakeUp: Failed to post a message (Not enough quota is available to process this command.)



## Results

### Eigenmodes

In [ ]:
design_analysis.get_eigenmode_results()

### Cross Kerr

In [ ]:
design_analysis.get_cross_kerr_matrix(iteration=-1)

## Update parameters

In [ ]:
design_analysis.overwrite_parameters()

## Close

In [ ]:
from qdesignoptimizer.utils.utils import close_ansys

close_ansys()